version: '2'
services:
  codeceptjs-bdd-oranum:
    # image: codeceptjs/codeceptjs
    environment:
        - TAG
        - CROSSBROWSER
    build:
      context: .
    depends_on:
      - firefox
      - web
    volumes:
      - .:/tests
  web:
    image: node
    command: node app/server.js
    volumes:
      - .:/app
  firefox:
    image: selenium/standalone-firefox-debug:2.53.0
    ports:
      - '4444'
      - '5900'
